
---

- name: Executes a command and responds to prompts
  hosts: muni1
  tasks:
   - name: Generic question with multiple different responses
     expect:
       command: /path/to/custom/command
       responses:
         Question:
           - response1
           - response2
           - response3
